# A default configuration to create a book with d2lbook.

[project]

# The project name, used as the filename of the package and the PDF file. For
# example, if set to d2l-book, then will build d2l-book.zip and d2l-book.pdf
name = tirx

# Book title. It will be displayed on the top-right of the HTML page and the
# front page of the PDF file
title = TIRx: High-Performance GPU Kernel Programming

# All author names
author = MLC Community

# Current release version
release = 0.0.1

# The copyright
copyright =

# The langunage, such as en, zh, ja, ...
lang = en

[translation]

origin_repo =
origin_lang =

# aws or gcp
translator =
terminology =


[build]

# The root page
index = index

# A list of wildcards to indicate the markdown files that need to be evaluated as
# Jupyter notebooks.
notebooks = **/*.md

# A list of wildcards to indicate the rsts files that need to be included
rsts =

# A list of markdown files that will be included but not evaluated as Jupyter
# notebooks. They are included in the eval outputs as markdown files (e.g.,
# _build/eval) but not in the rst, pdf, html outputs (e.g., _build/rst etc.)
non-notebooks =

# Files that will be skipped.
exclusions = **/README.md

# A list of files, if anyone is modified after the last build, will re-build all
# documents.
dependencies =

# A list of files that will be copied to the build folder.
resources = img/ setup.py static/ references.bib

# If True (default), then will evaluate the notebook to obtain outputs.
eval_notebook = False

# Pattern to identify notebooks that need GPU resources
gpu_pattern = chapter


# Source directory
source_dir = .

# Output directory
output_dir = _build

# If True, the mark the build as failed for any warning. Default is False.
warning_is_error = False

# Additional Sphinx extensions
sphinx_extensions =

# Additional Sphinx configuration options
sphinx_configs = mathjax_path = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"
    exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'img/scripts']

# Specify the tabs, seperated by ",". The first one will be the default tab.
tabs =

[html]

# A list of links that is displayed on the navbar. Each line contains a link, a
# link consists of three items: name, URL, and a fontawesome icon
# (https://fontawesome.com/icons?d=gallery). Items are seperated by ,
header_links =

# The filename of the favicon
favicon = static/mlc-favicon.ico

# The filename of the html logo
html_logo = static/mlc-logo-with-text-landscape.svg

# A list of CSS files to be included
include_css = static/custom.css

# A list of JS files to be included
include_js =

[pdf]

main_font =
sans_font =
mono_font =
post_latex =
latex_logo =
bibfile = references.bib


[library]

save_filename =
save_mark =
save_patterns =
version =
version_file =
root_dir =

[deploy]

google_analytics_tracking_id =
github_repo =
s3_bucket =
other_file_s3urls =


[colab]

github_repo =
exclusions = *.html **/index.html
libs =
libs_header = The following additional libraries are needed to run this
            notebook. Note that running on Colab is experimental, please report a Github
            issue if you have any problem.
gpu_pattern = chapter
replace_svg_url =


[sagemaker]

github_repo =
kernel = conda_python3
libs =
libs_header = Installing (updating) the following libraries for your Sagemaker
            instance.

[slides]

top_left =
top_right =
github_repo =
